[theme]
base = "light"
primaryColor = "#147EAF"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2A44"
font = "sans serif"

[theme.light.sidebar]
backgroundColor = "#40566C"
secondaryBackgroundColor = "#4D637A"
textColor = "#FFFFFF"
borderColor = "#40566C"
