[theme]
base = "light"
primaryColor = "#147EAF"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2A44"
font = "sans serif"

[theme.light.sidebar]
backgroundColor = "#EAF0F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#263B70"
borderColor = "#C8D6E3"
